services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.13-rc0
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodb:/data/db
    networks:
      - whatsapp

  postgres:
    image: postgres:15.3-alpine
    container_name: postgre
    ports:
      - ${POSTGRES_PORT}:5432    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgre:/var/lib/postgresql/data
    networks:
      - whatsapp

  redis:
    container_name: redis
    image: redis:7.4    
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
    networks:
      - whatsapp

volumes:
  mongodb:
  postgre:
  redis:

networks:
  whatsapp: